### PR TITLE
Add Flutter in #Implementations

### PR DESCRIPTION
**Pull request by kwent**

### CODE REVIEW

**Comment by PeterZainzinger** [comment]
There is now a [pure dart implemenation](https://github.com/Solido/Flutter-BlurHash) - I think that's the cleaner approach.

**Comment by kwent** [comment]
Even better !

**Comment by freitzzz** [comment]
> There is now a [pure dart implemenation](https://github.com/Solido/Flutter-BlurHash) - I think that's the cleaner approach.

I think you have mistaken the repository reference. This is the pure dart implementation with no flutter dependencies.

https://github.com/justacid/blurhash-dart

**Comment by DagAgren** [comment]
This is conflicting now. Could you fix it?

**Comment by kwent** [comment]
@DagAgren Done

**Pull request closed without merging**
